[package]
name = "embedded-error"
version = "0.1.0"
authors = ["Daniel Egger <daniel.egger@eggers-club.de>"]
edition = "2018"
categories = [
    "embedded",
    "no-std",
]
description = "Universal error types for embedded projects"
license = "MIT OR Apache-2.0"


